config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'
  
  resources :artists do
    resources :albums
  end
  
  scope 'albums/:album_id', as: 'album' do
    resources :songs, only: [:new, :create]
  end
  
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :song
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_artist
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = @artist.albums
  end

  def show
  end

  def new
    @album = @artist.albums.new

  end

  def edit


  end

  def create
    @album = @artist.albums.new(album_params)

    if @album.save
      redirect_to [@artist, @album]
    else
      render :new
    end
  end

  def update
    if @album.update(album_params)
      redirect_to [@artist, @album]
    else
      render :edit
    end
  end

  def destroy
    @album.destroy
    redirect_to artist_albums_path
  end

  private
    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:title, :year, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :update, :edit, :destroy]


  def index
    @artists = Artist.all 
  end

  def show
  end
  
  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save 
      redirect_to artists_path
    else 
      render :new
    end 
  end 

  def update 
    if @artist.update(artist_params)
      redirect_to @artist
    else 
      render :edit 
    end 
  end 

  def destroy 
    @artist.destroy 
    redirect_to artists_path
  end 

  
  private 

  def set_artist
    @artist = Artist.find(params[:id])
  end 

  def artist_params
    params.require(:artist).permit(:name)
  end 

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_album

  def new
    @song = Song.new
  end

  def create
    @song = @album.song.new(song_params)
    if @song.save
      redirect_to artist_album_path(@album.artist_id, @album)
    else
      render :new
    end
  end

  private
  def set_album
    @album = Album.find(params[:album_id])
  end


    def song_params
      params.require(:song).permit(:name, :length)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_form.html.erb
<h1><%= @album.id ? 'Edit Album' : 'Create Album' %></h1>
<hr />
<%= form_for [@artist, @album] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <br />
  <%= f.label :year %>
  <%= f.text_area :year, required: true %>
  <br />
  <%= f.label :description %>
  <%= f.text_area :description, required: true %>

  <%= f.submit %>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit an Album</h1>
<%= render 'form' %>

app/views/albums/index.html.erb
<h1>Click to Check Out an Album </h1>
<hr>
<%= link_to 'Create a New Album', new_artist_album_path(@artist) %>
<ul>
  <% @albums.each do |album| %>
    <li><%= link_to album.name, [@artist, album] %></li>
  <% end %>
</ul>

app/views/albums/new.html.erb
<h1>Add New Album</h1>
<%= render 'form' %>

app/views/albums/show.html.erb
<h1><%= @artist.name %> - <%= @album.title %></h1>
<p><%= @album.year %></p>
<p><%= @album.description %></p>


<br>
<%= link_to 'Edit Album', edit_artist_album_path([@artist, @album]) %>
<br>
<%= link_to 'Delete Album', [@artist, @song], method: :delete %>
<br>
<%= link_to 'Add Song', new_album_song_path(@album) %>
<br>
<%= link_to 'Back To Artist', artist_album_path(@artist) %>

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit an Artist</h1>
<%= render 'form' %>

app/views/artists/index.html.erb
<h1>Click a Sub To View Content</h1>
<%= link_to 'Create a New Artist', new_artist_path %>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist %></li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h1>Create a New Artist /h1>
<%= render 'form' %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Artists', artist_albums_path(@artist) %>
<br />
<%= link_to 'Edit Artist', edit_artist_path(@artist) %>
<br />
<%= link_to 'Delete Artist', @artist, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompactDisc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_song.html.erb
<hr />
<p>Title: <%= song.name %></p>
<p><strong><%= song.length %></strong></p>
</hr>

app/views/songs/new.html.erb
<h1>Add A Song</h1>
<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.label :length %>
  <%= f.text_field :length, required: true %>
  <br />
  <%= f.submit %>
<% end %>